In [1]:
import numpy as np

In [98]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [99]:
 b=np.array([1,2,3,4][1,4,5,6]) #ERROR BECAUSE TWO DIM 2 BRACKETS

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-99-1592868dd0b5>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  b=np.array([1,2,3,4][1,4,5,6]) #ERROR BECAUSE TWO DIM 2 BRACKETS


TypeError: list indices must be integers or slices, not tuple

In [100]:
b=np.array([[1.0,2.0,3.0,4.0],[2,4,5,6]])
b

array([[1., 2., 3., 4.],
       [2., 4., 5., 6.]])

In [101]:
b.ndim # TO FIND DIMENSION

2

In [102]:
a.ndim

1

In [103]:
b.shape()

TypeError: 'tuple' object is not callable

In [104]:
b.shape

(2, 4)

In [105]:
b.dtype

dtype('float64')

In [106]:
 a.dtype

dtype('int32')

In [107]:
b[1,2] #SPECIFIC ELEMENT 2nd ROW 3rdELEMENT

5.0

In [108]:
b[:,0] #SPECIFIC COLUMN

array([1., 2.])

In [109]:
b[1:4:2] #[start index:endindex:step]

array([[2., 4., 5., 6.]])

In [110]:
# IF WE WANT IN FIRST ROW
b[1,0:4:2]

array([2., 5.])

In [111]:
b

array([[1., 2., 3., 4.],
       [2., 4., 5., 6.]])

In [116]:
b[0,2]=10
    
    #TO CHNAGE SPECIFIC VALUE

In [119]:
b[1,3]=12
b

array([[ 1.,  2., 10.,  4.],
       [ 2.,  4.,  5., 12.]])

In [120]:
b[:,1]=9
b   # CHANGING ALL ROWS & 2ND COLUMN VALUE TO 9

array([[ 1.,  9., 10.,  4.],
       [ 2.,  9.,  5., 12.]])

In [122]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [125]:
np.ones([2,3,2],dtype='int32') #3 DIMENSION with dtype=32

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [128]:
np.full((2,2),99) # fulling the matrix with 99

array([[99, 99],
       [99, 99]])

In [133]:
np.full((6,2),12)

array([[12, 12],
       [12, 12],
       [12, 12],
       [12, 12],
       [12, 12],
       [12, 12]])

In [134]:
np.full(a,4) #ALLOTING A WITH 4

array([[[4, 4, 4],
        [4, 4, 4]]])

In [138]:
np.full(b.shape,5) #FOR MORETHAN 1 MATRIX WE SHOULD USE .SHAPE

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [140]:
np.full_like(b,4)

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [141]:
np.random.rand((2,3)) # IF THE ERROR IS TUPLE REMOVE BRACKET

TypeError: 'tuple' object cannot be interpreted as an integer

In [143]:
np.random.rand(2,3,3)

array([[[0.87191689, 0.17778607, 0.25548278],
        [0.51720524, 0.21953937, 0.90071874],
        [0.53887023, 0.94365049, 0.71534035]],

       [[0.85402746, 0.18600545, 0.54068827],
        [0.98124596, 0.54291349, 0.89073427],
        [0.04972334, 0.32185285, 0.63394552]]])

In [146]:
np.random.rand(2,3)

array([[0.22499104, 0.85162635, 0.71742614],
       [0.6751443 , 0.00739017, 0.60970248]])

In [150]:
np.random.randint(0,12,8)

array([ 0,  4,  3,  4, 11,  2,  6,  6])

In [151]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [152]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [156]:
arr=np.array([[1,2,3]])
np.repeat(arr,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [157]:
np.repeat(arr,3,axis=0)#IF WE SPEIFY AXIS=0 IT START LIKE 3*3 MATRIX

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [173]:
a=np.ones([5,5],dtype=int)
a


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [166]:
a[1,1:4]=0
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [168]:
a[2:4,1]=0
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 1, 1, 1],
       [1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [169]:
a[3,2:4]=0
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [170]:
a[2,3]=0
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 1, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [171]:
a[2,2]=9
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [175]:
b=np.ones([5,5],dtype=int)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [185]:
 c=np.zeros([3,3])
c[1,1]=9
c

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [190]:
 b[1:4,1:4]=c # JUST REPLACE B[1:4,1:4] ELEMENTS WITH C
b


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [196]:
d=c.copy() # IF WE DO THIS WE HAVE NO IMPACT ON ORIGINAL ARRAY
d

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [197]:
d[0]=1

In [198]:
d

array([[1., 1., 1.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [199]:
c

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [203]:
#USING ARRAYS WE CAN DO CALCULATIONS EASILY LIKE
c+2

array([[ 2.,  2.,  2.],
       [ 2., 11.,  2.],
       [ 2.,  2.,  2.]])

In [204]:
c*2

array([[ 0.,  0.,  0.],
       [ 0., 18.,  0.],
       [ 0.,  0.,  0.]])

In [205]:
c/2

array([[0. , 0. , 0. ],
       [0. , 4.5, 0. ],
       [0. , 0. , 0. ]])

In [206]:
c*2+2/2

array([[ 1.,  1.,  1.],
       [ 1., 19.,  1.],
       [ 1.,  1.,  1.]])

In [208]:
np.sin(c) # NP.SIN()

array([[0.        , 0.        , 0.        ],
       [0.        , 0.41211849, 0.        ],
       [0.        , 0.        , 0.        ]])

# LINEAR ALGEBRA


In [219]:
a=np.ones([2,3])
a


array([[1., 1., 1.],
       [1., 1., 1.]])

In [220]:
b=np.full((3,2),3)
b

array([[3, 3],
       [3, 3],
       [3, 3]])

In [221]:
a*b #IT GIVES ERRORS BECAUSE OF DIFFWERENT SIXE

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [224]:
k=np.matmul(a,b) #SO, WE USE MATMUL(A,B) FUNCTION
k

array([[9., 9.],
       [9., 9.]])

In [225]:
# FIND THE DETERMINENT IN ALGEBRA
np.linalg.det(k) # 9*9-9*9

0.0

In [227]:
m=np.identity(3)
np.linalg.det(m)

1.0

In [228]:
k.reshape((4)) # RESHAPES MATRIX

array([9., 9., 9., 9.])

In [229]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [231]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [232]:
# To retrive from data
filedata = np.genfromtxt('data.txt', delimiter=',')

OSError: data.txt not found.